# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Kyle Galloway
tagline:             Computer Science Student at The University of Alabama
url:                 http://kylegalloway.me
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Kyle Galloway
  url:               http://kylegalloway.me
  email:             kyle.galloway@gmail.com

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/kylegalloway/kylegalloway.github.io

# This is the list of pages to incldue in the header of the website.
pages_list:       {'About':'/about','Archive':'/archive','Feed':'/atom.xml'}